image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva
    - k--kato.intellij-idea-keybindings
    - mechatroner.rainbow-csv
    - vscodevim.vim

- name: database
  port: 5432
  onOpen: ignore

- name: create tables in db
  command: './init-db.sh'