image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva
    - k--kato.intellij-idea-keybindings
    - mechatroner.rainbow-csv
    - vscodevim.vim

tasks:
  - name: create tables in db
    init: sleep 5; './init-db.sh'

ports:
  - name: back-end
    port: 3000
    onOpen: ignore
    visibility: public
  - name: database
    port: 5432
    onOpen: ignore